server:
  port: 8081

#database 연동 설정
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Ushouse
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Ushouse2023
  jpa:
   open-in-view: false
   generate-ddl: true
   show-sql: true
   hibernate:
      ddl-auto: update
  
logging:
  level:
   '[org.springframework ]': debug
   '[org.springframework.web]': debug
   
jwt:
  header: Authorization
  secret:
    key: 2r5u8x/A?D*G-KaPdSgVkYp3s6v9y$B&
